.TH "Referencia del directorio C:/Users/Emi/Documents/Repositorios/Ramirez_2C_2026/firmware/projects/G2_Ejer_4/main" 3 "Version 1.0" "G2_Ejer_4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio C:/Users/Emi/Documents/Repositorios/Ramirez_2C_2026/firmware/projects/G2_Ejer_4/main
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBG2_Ejer_4\&.c\fP"
.br
.in -1c
