.TH "Referencia del directorio C:/Users/Emi/Documents/Repositorios/Ramirez_2C_2026/firmware/projects/G2_Ejer_1/main" 3 "Version 1.0" "G2_Ejer_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio C:/Users/Emi/Documents/Repositorios/Ramirez_2C_2026/firmware/projects/G2_Ejer_1/main
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBG2_Ejer_1\&.c\fP"
.br
.RI "Aplicación de medición de distancia con sensor HC-SR04, display LCD y LEDs mediante FreeRTOS\&. "
.in -1c
