.TH "Referencia del directorio C:/Users/Emi/Documents/Repositorios/Ramirez_2C_2026/firmware/projects" 3 "Version 1.0" "G2_Ejer_3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio C:/Users/Emi/Documents/Repositorios/Ramirez_2C_2026/firmware/projects
.SH SYNOPSIS
.br
.PP
.SS "Directorios"

.in +1c
.ti -1c
.RI "directorio \fBG2_Ejer_3\fP"
.br
.in -1c
